### PR TITLE
Create barebones for Qiskit Camp 2020

### PR DESCRIPTION
**Pull request by delapuente**
Fix qiskit/qiskit.org#346

### CODE REVIEW

**Comment by lerongil** [comment]
I don't see the camp preview pages - are they down?

**Comment by delapuente** [comment]
The routes are not exposed anywhere in the community site :( but they are alive:
https://communityqiskitorg-git-drafting-qiskit-camp-2020.neosalvador.now.sh/events/camp-2020

**Comment by delapuente** [comment]
@justjosie @KallieFerguson I need a header picture for the new site. Could you provide one, please?

**Comment by delapuente** [comment]
Closing in favour of qiskit/qiskit.org#362

**Pull request closed without merging**
